name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake g++ libgtest-dev

    - name: Build Google Test
      run: |
        mkdir -p ~/googletest
        cd ~/googletest
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo cp lib/libgtest.a /usr/lib/
        sudo cp lib/libgtest_main.a /usr/lib/

    - name: Configure CMake
      run: |
        cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ./build/calculator_test